"""empty message

Revision ID: 10b76babf4e7
Revises: 98afd0240f46
Create Date: 2017-05-08 11:38:25.765969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b76babf4e7'
down_revision = '98afd0240f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('beer_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('snack_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_beer_id'), 'items', ['beer_id'], unique=False)
    op.create_index(op.f('ix_items_snack_id'), 'items', ['snack_id'], unique=False)
    op.drop_index('ix_items_item_id', table_name='items')
    op.create_foreign_key(None, 'items', 'snacks', ['snack_id'], ['id'])
    op.create_foreign_key(None, 'items', 'beers', ['beer_id'], ['id'])
    op.drop_column('items', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_index('ix_items_item_id', 'items', ['item_id'], unique=False)
    op.drop_index(op.f('ix_items_snack_id'), table_name='items')
    op.drop_index(op.f('ix_items_beer_id'), table_name='items')
    op.drop_column('items', 'snack_id')
    op.drop_column('items', 'beer_id')
    # ### end Alembic commands ###
