"""empty message

Revision ID: 263b4ce62e2e
Revises: 8aa000fdcf90
Create Date: 2017-05-27 23:46:47.574570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263b4ce62e2e'
down_revision = '8aa000fdcf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_itens_item_id'), 'return_itens', ['item_id'], unique=False)
    op.create_index(op.f('ix_return_itens_order_id'), 'return_itens', ['order_id'], unique=False)
    op.add_column('item_orders', sa.Column('returned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_orders', 'returned')
    op.drop_index(op.f('ix_return_itens_order_id'), table_name='return_itens')
    op.drop_index(op.f('ix_return_itens_item_id'), table_name='return_itens')
    op.drop_table('return_itens')
    # ### end Alembic commands ###
