"""empty message

Revision ID: 3baaffc6234c
Revises: 10b76babf4e7
Create Date: 2017-05-08 22:59:25.887627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baaffc6234c'
down_revision = '10b76babf4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
