"""empty message

Revision ID: 3f32b9347de2
Revises: 85e3d067b313
Create Date: 2017-05-07 15:56:19.253761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f32b9347de2'
down_revision = '85e3d067b313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'type')
    # ### end Alembic commands ###
