"""empty message

Revision ID: 5466da89e60a
Revises: a7b04abd6b74
Create Date: 2017-06-17 16:25:41.500727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5466da89e60a'
down_revision = 'a7b04abd6b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_itens', sa.Column('item_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_itens', 'item_value')
    # ### end Alembic commands ###
