"""empty message

Revision ID: 6160d11d7333
Revises: 3f32b9347de2
Create Date: 2017-05-07 16:28:42.878105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6160d11d7333'
down_revision = '3f32b9347de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total_value')
    # ### end Alembic commands ###
