"""empty message

Revision ID: 85e3d067b313
Revises: c161011abf5e
Create Date: 2017-05-07 14:46:57.221079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e3d067b313'
down_revision = 'c161011abf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_orders_item_id'), 'item_orders', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_orders_order_id'), 'item_orders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_orders_order_id'), table_name='item_orders')
    op.drop_index(op.f('ix_item_orders_item_id'), table_name='item_orders')
    op.drop_table('item_orders')
    # ### end Alembic commands ###
