"""empty message

Revision ID: 98afd0240f46
Revises: 6160d11d7333
Create Date: 2017-05-08 10:55:52.758026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98afd0240f46'
down_revision = '6160d11d7333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beers', sa.Column('mark', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beers', 'mark')
    # ### end Alembic commands ###
