"""empty message

Revision ID: a7b04abd6b74
Revises: 33803d062d93
Create Date: 2017-06-15 22:35:51.171637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b04abd6b74'
down_revision = '33803d062d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_itens', sa.Column('item_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_itens', 'item_quantity')
    # ### end Alembic commands ###
