"""empty message

Revision ID: a80e74dbc5ab
Revises: 263b4ce62e2e
Create Date: 2017-06-10 16:08:13.233538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80e74dbc5ab'
down_revision = '263b4ce62e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_orders', sa.Column('confirm_return', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_orders', 'confirm_return')
    # ### end Alembic commands ###
