"""empty message

Revision ID: c52b7fa3b6fb
Revises: 3baaffc6234c
Create Date: 2017-05-13 15:06:39.300574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b7fa3b6fb'
down_revision = '3baaffc6234c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'city')
    # ### end Alembic commands ###
