"""empty message

Revision ID: de91cb34508b
Revises: f2ae1fc1b5fa
Create Date: 2017-06-18 15:05:19.567556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de91cb34508b'
down_revision = 'f2ae1fc1b5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_exchanges', sa.Column('item_to_exchange', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_exchanges', 'item_to_exchange')
    # ### end Alembic commands ###
