"""empty message

Revision ID: eb0d55894cb9
Revises: de91cb34508b
Create Date: 2017-06-18 18:43:47.756901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb0d55894cb9'
down_revision = 'de91cb34508b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchanges_delivery_address_id', table_name='exchanges')
    op.drop_constraint('exchanges_delivery_address_id_fkey', 'exchanges', type_='foreignkey')
    op.drop_column('exchanges', 'fare')
    op.drop_column('exchanges', 'delivery_address_id')
    op.add_column('item_exchanges', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('item_exchanges', sa.Column('total_value', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('exchange', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'exchange')
    op.drop_column('item_exchanges', 'total_value')
    op.drop_column('item_exchanges', 'quantity')
    op.add_column('exchanges', sa.Column('delivery_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exchanges', sa.Column('fare', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_foreign_key('exchanges_delivery_address_id_fkey', 'exchanges', 'address', ['delivery_address_id'], ['id'])
    op.create_index('ix_exchanges_delivery_address_id', 'exchanges', ['delivery_address_id'], unique=False)
    # ### end Alembic commands ###
