"""empty message

Revision ID: f2ae1fc1b5fa
Revises: 5466da89e60a
Create Date: 2017-06-18 14:43:31.464168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ae1fc1b5fa'
down_revision = '5466da89e60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('delivery_address_id', sa.Integer(), nullable=True),
    sa.Column('fare', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delivery_address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_client_id'), 'exchanges', ['client_id'], unique=False)
    op.create_index(op.f('ix_exchanges_delivery_address_id'), 'exchanges', ['delivery_address_id'], unique=False)
    op.create_table('item_exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_exchanges_exchange_id'), 'item_exchanges', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_item_exchanges_item_id'), 'item_exchanges', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_exchanges_item_id'), table_name='item_exchanges')
    op.drop_index(op.f('ix_item_exchanges_exchange_id'), table_name='item_exchanges')
    op.drop_table('item_exchanges')
    op.drop_index(op.f('ix_exchanges_delivery_address_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_client_id'), table_name='exchanges')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
